// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ChemistryUIClient is the client API for ChemistryUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChemistryUIClient interface {
	// ListEngineSpecs returns a list of Chemistry Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (ChemistryUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type chemistryUIClient struct {
	cc grpc.ClientConnInterface
}

func NewChemistryUIClient(cc grpc.ClientConnInterface) ChemistryUIClient {
	return &chemistryUIClient{cc}
}

func (c *chemistryUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (ChemistryUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &ChemistryUI_ServiceDesc.Streams[0], "/v1.ChemistryUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &chemistryUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ChemistryUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type chemistryUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *chemistryUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *chemistryUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.ChemistryUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChemistryUIServer is the server API for ChemistryUI service.
// All implementations must embed UnimplementedChemistryUIServer
// for forward compatibility
type ChemistryUIServer interface {
	// ListEngineSpecs returns a list of Chemistry Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, ChemistryUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedChemistryUIServer()
}

// UnimplementedChemistryUIServer must be embedded to have forward compatible implementations.
type UnimplementedChemistryUIServer struct {
}

func (UnimplementedChemistryUIServer) ListEngineSpecs(*ListEngineSpecsRequest, ChemistryUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedChemistryUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedChemistryUIServer) mustEmbedUnimplementedChemistryUIServer() {}

// UnsafeChemistryUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChemistryUIServer will
// result in compilation errors.
type UnsafeChemistryUIServer interface {
	mustEmbedUnimplementedChemistryUIServer()
}

func RegisterChemistryUIServer(s grpc.ServiceRegistrar, srv ChemistryUIServer) {
	s.RegisterService(&ChemistryUI_ServiceDesc, srv)
}

func _ChemistryUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChemistryUIServer).ListEngineSpecs(m, &chemistryUIListEngineSpecsServer{stream})
}

type ChemistryUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type chemistryUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *chemistryUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _ChemistryUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChemistryUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ChemistryUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChemistryUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChemistryUI_ServiceDesc is the grpc.ServiceDesc for ChemistryUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChemistryUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.ChemistryUI",
	HandlerType: (*ChemistryUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _ChemistryUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _ChemistryUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "chemistry-ui.proto",
}
